---
Resources:
    Bucket:
        Type: 'AWS::S3::Bucket'

    BucketPolicy:
        Type: 'AWS::S3::BucketPolicy'
        Properties:
            Bucket: !Ref 'Bucket'
            PolicyDocument:
                Statement:
                    - Action:  's3:PutObject'
                      Effect: 'Allow'
                      Resource: !Join ['', ['arn:aws:s3:::', !Ref 'Bucket', '/teller-responses/*']]
                      Principal: '*'

    DumpTellerResponseLambdaRole:
        Type: 'AWS::IAM::Role'
        Properties:
            AssumeRolePolicyDocument:
                Version: '2012-10-17'
                Statement:
                    - Effect: Allow
                      Principal:
                          Service:
                              - 'lambda.amazonaws.com'
                      Action:
                          - 'sts:AssumeRole'
            ManagedPolicyArns:
                 - "arn:aws:iam::aws:policy/AWSLambdaExecute"
            Policies:
                - PolicyName: "S3Access"
                  PolicyDocument:
                      Version: "2012-10-17"
                      Statement:
                          - Effect: "Allow"
                            Action: "s3:PutObject"
                            Resource: !Join ['', ['arn:aws:s3:::', !Ref 'Bucket', '/teller-responses/*']]
