---
Parameters:
    LatestPackageVersion:
        Type: String
    PackageBucket:
        Type: String
    PackageKey:
        Type: String
    TellerAuth:
        Type: String

Outputs:
    DiffAlertLambdaFunctionName:
        Value: !GetAtt ['DiffAlertLambdaFunction', 'Arn']

Resources:
    Bucket:
        Type: 'AWS::S3::Bucket'

    BucketPolicy:
        Type: 'AWS::S3::BucketPolicy'
        Properties:
            Bucket: !Ref Bucket
            PolicyDocument:
                Statement:
                    - Action:  's3:PutObject'
                      Effect: 'Allow'
                      Resource: !Join ['', ['arn:aws:s3:::', !Ref Bucket, '/teller-responses/*']]
                      Principal: '*'

    DumpTellerResponseLambdaRole:
        Type: 'AWS::IAM::Role'
        Properties:
            AssumeRolePolicyDocument:
                Version: '2012-10-17'
                Statement:
                    - Effect: Allow
                      Principal:
                          Service:
                              - 'lambda.amazonaws.com'
                      Action:
                          - 'sts:AssumeRole'
            ManagedPolicyArns:
                 - "arn:aws:iam::aws:policy/AWSLambdaExecute"
            Policies:
                - PolicyName: "S3Access"
                  PolicyDocument:
                      Version: "2012-10-17"
                      Statement:
                          - Effect: "Allow"
                            Action: "s3:PutObject"
                            Resource: !Join ['', ['arn:aws:s3:::', !Ref Bucket, '/teller-responses/*']]

    DumpTellerLambdaFunction:
        Type: 'AWS::Lambda::Function'
        Properties:
            Code:
                S3Bucket: !Ref PackageBucket
                S3Key: !Ref PackageKey
                S3ObjectVersion: !Ref LatestPackageVersion
            Description: 'Makes a couple reqeusts to the Teller API and dumps the responses to S3.'
            Environment:
                Variables:
                    AUTH: !Ref TellerAuth
                    BUCKET: !Ref Bucket
            Handler: 'src/dump-teller-responses.index'
            Role: !GetAtt ['DumpTellerResponseLambdaRole', 'Arn']
            Runtime: 'nodejs6.10'
            Timeout: 30

    DiffAlertLambdaRole:
        Type: 'AWS::IAM::Role'
        Properties:
            AssumeRolePolicyDocument:
                Version: '2012-10-17'
                Statement:
                    - Effect: Allow
                      Principal:
                          Service:
                              - 'lambda.amazonaws.com'
                      Action:
                          - 'sts:AssumeRole'
            ManagedPolicyArns:
                 - "arn:aws:iam::aws:policy/AWSLambdaExecute"
            Policies:
                - PolicyName: "S3Access"
                  PolicyDocument:
                      Version: "2012-10-17"
                      Statement:
                          - Effect: "Allow"
                            Action: "s3:GetObject"
                            Resource: !Join ['', ['arn:aws:s3:::', !Ref Bucket, '/*']]

    DiffAlertLambdaFunction:
        Type: 'AWS::Lambda::Function'
        Properties:
            Code:
                S3Bucket: !Ref PackageBucket
                S3Key: !Ref PackageKey
                S3ObjectVersion: !Ref LatestPackageVersion
            Description: 'Diffs a new S3 object against an older one, and alerts if there is a difference.'
            Handler: 'src/router.diff_alert'
            Role: !GetAtt ['DiffAlertLambdaRole', 'Arn']
            Runtime: 'nodejs6.10'
            Timeout: 30
